import {createClient} from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
import {SUPABASE_URL,SUPABASE_ANON_KEY} from "./supabase-config.js";
const supabase=createClient(SUPABASE_URL,SUPABASE_ANON_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=s=>document.querySelector(s);
const e={loading:$("#career-loading"),auth:$("#career-auth-required"),view:$("#career-view"),logout:$("#logout-button"),newBtn:$("#new-application-button"),dialog:$("#application-dialog"),form:$("#application-form"),close:$("#dialog-close"),cancel:$("#cancel-application-button"),remove:$("#delete-application-button"),save:$("#save-application-button"),id:$("#application-id"),company:$("#company"),role:$("#role"),date:$("#applied-at"),status:$("#status"),source:$("#source"),model:$("#work-model"),location:$("#location"),salary:$("#salary"),url:$("#job-url"),notes:$("#notes"),msg:$("#form-message"),search:$("#career-search"),statusFilter:$("#status-filter"),period:$("#period-filter"),list:$("#applications-list"),empty:$("#applications-empty"),warning:$("#career-setup-warning"),count:$("#applications-count"),total:$("#kpi-total"),active:$("#kpi-active"),interviews:$("#kpi-interviews"),rate:$("#kpi-response-rate"),title:$("#application-dialog-title")};
let rows=[],ready=true;
const terminal=new Set(["Oferta","Reprovado","Desistência"]);
const advanced=new Set(["Em análise","Entrevista","Case/Teste","Oferta","Reprovado","Desistência"]);
const interview=new Set(["Entrevista","Case/Teste","Oferta"]);
const esc=v=>String(v??"").replace(/[&<>"\']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","\'":"&#039;"}[c]));
const fmt=d=>d?d.split("-").reverse().join("/"):"—";
const today=()=>{const n=new Date(),l=new Date(n.getTime()-n.getTimezoneOffset()*60000);return l.toISOString().slice(0,10)};
function openForm(r){e.form.reset();e.id.value="";e.date.value=today();e.status.value="Candidatado";e.remove.hidden=true;e.title.textContent="Nova candidatura";if(r){e.id.value=r.id;e.company.value=r.company||"";e.role.value=r.role||"";e.date.value=r.applied_at||today();e.status.value=r.status||"Candidatado";e.source.value=r.source||"";e.model.value=r.work_model||"";e.location.value=r.location||"";e.salary.value=r.salary||"";e.url.value=r.job_url||"";e.notes.value=r.notes||"";e.remove.hidden=false;e.title.textContent="Editar candidatura"}e.dialog.showModal();setTimeout(()=>e.company.focus(),0)}
function closeForm(){if(e.dialog.open)e.dialog.close()}
function filtered(){const q=e.search.value.trim().toLowerCase(),s=e.statusFilter.value,p=e.period.value,now=new Date(),yr=now.getFullYear();return rows.filter(r=>{if(q&&!((r.company+" "+r.role).toLowerCase().includes(q)))return false;if(s!=="all"&&r.status!==s)return false;if(p!=="all"){const d=new Date(r.applied_at+"T12:00:00");if(p==="year"&&d.getFullYear()!==yr)return false;if(p==="30"||p==="90"){const c=new Date();c.setDate(c.getDate()-Number(p));if(d<c)return false}}return true})}
function render(){e.total.textContent=rows.length;e.active.textContent=rows.filter(r=>!terminal.has(r.status)).length;e.interviews.textContent=rows.filter(r=>interview.has(r.status)).length;e.rate.textContent=(rows.length?Math.round(rows.filter(r=>advanced.has(r.status)).length/rows.length*100):0)+"%";const data=filtered();e.count.textContent=data.length+" "+(data.length===1?"registro":"registros");e.empty.hidden=data.length!==0||!ready;e.list.innerHTML=data.map(r=>"<article class=\"application-row\" data-id=\""+esc(r.id)+"\"><div class=\"application-company\"><strong>"+esc(r.company)+"</strong><span>"+esc(r.source||"Fonte não informada")+"</span></div><div class=\"application-role\">"+esc(r.role)+"<span>"+esc(r.work_model||r.location||"Modelo não informado")+"</span></div><time class=\"application-date\">"+fmt(r.applied_at)+"</time><span class=\"status-badge\">"+esc(r.status)+"</span><button class=\"row-menu\" type=\"button\" aria-label=\"Editar\">•••</button></article>").join("");e.list.querySelectorAll(".application-row").forEach(n=>n.querySelector("button").onclick=()=>openForm(rows.find(r=>String(r.id)===n.dataset.id)))}
async function load(){ready=true;e.warning.hidden=true;const{data,error}=await supabase.from("career_applications").select("*").order("applied_at",{ascending:false}).order("created_at",{ascending:false});if(error){if(error.code==="42P01"||/career_applications|schema cache|does not exist/i.test(error.message||"")){ready=false;rows=[];e.warning.hidden=false;render();return}throw error}rows=data||[];render()}
e.form.onsubmit=async ev=>{ev.preventDefault();if(!e.form.checkValidity()){e.form.reportValidity();return}const{data:{user}}=await supabase.auth.getUser();if(!user)return;e.save.disabled=true;e.save.textContent="Salvando…";const payload={user_id:user.id,company:e.company.value.trim(),role:e.role.value.trim(),applied_at:e.date.value,status:e.status.value,source:e.source.value||null,work_model:e.model.value||null,location:e.location.value.trim()||null,salary:e.salary.value.trim()||null,job_url:e.url.value.trim()||null,notes:e.notes.value.trim()||null};const q=e.id.value?supabase.from("career_applications").update(payload).eq("id",e.id.value):supabase.from("career_applications").insert(payload);const{error}=await q;e.save.disabled=false;e.save.textContent="Salvar candidatura";if(error){e.msg.textContent="Não foi possível salvar. Verifique a configuração do banco.";e.msg.classList.add("is-error");return}closeForm();await load()};
e.remove.onclick=async()=>{if(!e.id.value||!confirm("Excluir esta candidatura?"))return;await supabase.from("career_applications").delete().eq("id",e.id.value);closeForm();await load()};
e.newBtn.onclick=()=>ready?openForm():e.warning.scrollIntoView({behavior:"smooth"});
e.close.onclick=e.cancel.onclick=closeForm;
e.search.oninput=render;e.statusFilter.onchange=e.period.onchange=render;
e.logout.onclick=async()=>{await supabase.auth.signOut();location.href="./"};
(async()=>{const{data:{session}}=await supabase.auth.getSession();e.loading.hidden=true;if(!session){e.auth.hidden=false;return}e.view.hidden=false;try{await load()}catch{e.warning.hidden=false}})();