import * as XLSX from "https://cdn.sheetjs.com/xlsx-0.20.3/package/xlsx.mjs";
import {createClient} from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
import {SUPABASE_URL,SUPABASE_ANON_KEY} from "./supabase-config.js";
const supabase=createClient(SUPABASE_URL,SUPABASE_ANON_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=s=>document.querySelector(s);
const e={loading:$("#career-loading"),auth:$("#career-auth-required"),view:$("#career-view"),logout:$("#logout-button"),newBtn:$("#new-application-button"),exportBtn:$("#export-career-button"),dialog:$("#application-dialog"),form:$("#application-form"),close:$("#dialog-close"),cancel:$("#cancel-application-button"),remove:$("#delete-application-button"),save:$("#save-application-button"),id:$("#application-id"),company:$("#company"),role:$("#role"),date:$("#applied-at"),applicationDeadline:$("#application-deadline"),status:$("#status"),source:$("#source"),model:$("#work-model"),location:$("#location"),salary:$("#salary"),url:$("#job-url"),notes:$("#notes"),msg:$("#form-message"),search:$("#career-search"),statusFilter:$("#status-filter"),period:$("#period-filter"),list:$("#applications-list"),empty:$("#applications-empty"),warning:$("#career-setup-warning"),count:$("#applications-count"),total:$("#kpi-total"),active:$("#kpi-active"),interviews:$("#kpi-interviews"),rate:$("#kpi-response-rate"),title:$("#application-dialog-title")};
let rows=[],ready=true;
const terminal=new Set(["Oferta","Reprovado","Desistência"]);
const preApplicationStatus="Para candidatar";
const advanced=new Set(["Em análise","Entrevista","Case/Teste","Oferta","Reprovado","Desistência"]);
const interview=new Set(["Entrevista","Case/Teste","Oferta"]);
const esc=v=>String(v??"").replace(/[&<>"\']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","\'":"&#039;"}[c]));
const fmt=d=>d?d.split("-").reverse().join("/"):"—";
const daysSince=d=>{if(!d)return "";const start=new Date(d+"T12:00:00");const now=new Date();start.setHours(0,0,0,0);now.setHours(0,0,0,0);const days=Math.max(0,Math.floor((now-start)/86400000));return days===0?"Hoje":days===1?"Há 1 dia":"Há "+days+" dias"};
const today=()=>{const n=new Date(),l=new Date(n.getTime()-n.getTimezoneOffset()*60000);return l.toISOString().slice(0,10)};
function openForm(r){e.form.reset();e.id.value="";e.date.value="";e.applicationDeadline.value="";e.status.value="Para candidatar";e.remove.hidden=true;e.title.textContent="Nova candidatura";if(r){e.id.value=r.id;e.company.value=r.company||"";e.role.value=r.role||"";e.date.value=r.applied_at||"";e.applicationDeadline.value=r.application_deadline||"";e.status.value=r.status||"Para candidatar";e.source.value=r.source||"";e.model.value=r.work_model||"";e.location.value=r.location||"";e.salary.value=r.salary||"";e.url.value=r.job_url||"";e.notes.value=r.notes||"";e.remove.hidden=false;e.title.textContent="Editar candidatura"}e.dialog.showModal();setTimeout(()=>e.company.focus(),0)}
function closeForm(){if(e.dialog.open)e.dialog.close()}
function filtered(){const q=e.search.value.trim().toLowerCase(),s=e.statusFilter.value,p=e.period.value,now=new Date(),yr=now.getFullYear();return rows.filter(r=>{if(q&&!((r.company+" "+r.role).toLowerCase().includes(q)))return false;if(s!=="all"&&r.status!==s)return false;if(p!=="all"){const base=r.applied_at||r.created_at?.slice(0,10);if(!base)return false;const d=new Date(base+"T12:00:00");if(p==="year"&&d.getFullYear()!==yr)return false;if(p==="30"||p==="90"){const c=new Date();c.setDate(c.getDate()-Number(p));if(d<c)return false}}return true})}
function exportCareer(){const data=filtered();if(!data.length){alert("Não há registros para exportar com os filtros atuais.");return}const exportRows=data.map(r=>({"Empresa":r.company,"Vaga":r.role,"Status":r.status,"Data da candidatura":r.applied_at?fmt(r.applied_at):"","Prazo para candidatar":r.application_deadline?fmt(r.application_deadline):"","Fonte":r.source||"","Modelo":r.work_model||"","Localização":r.location||"","Faixa salarial":r.salary||"","Link da vaga":r.job_url||"","Observações":r.notes||""}));const ws=XLSX.utils.json_to_sheet(exportRows);ws["!cols"]=[{wch:24},{wch:32},{wch:18},{wch:20},{wch:22},{wch:16},{wch:14},{wch:20},{wch:18},{wch:42},{wch:45}];const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Carreira");XLSX.writeFile(wb,"carreira.xlsx")}
function render(){const applications=rows.filter(r=>r.status!==preApplicationStatus);e.total.textContent=applications.length;e.active.textContent=applications.filter(r=>!terminal.has(r.status)).length;e.interviews.textContent=applications.filter(r=>interview.has(r.status)).length;e.rate.textContent=(applications.length?Math.round(applications.filter(r=>advanced.has(r.status)).length/applications.length*100):0)+"%";const data=filtered();e.count.textContent=data.length+" "+(data.length===1?"registro":"registros");e.empty.hidden=data.length!==0||!ready;e.list.innerHTML=data.map(r=>"<article class=\"application-row\" data-id=\""+esc(r.id)+"\"><div class=\"application-company\"><strong>"+esc(r.company)+"</strong><span>"+esc(r.source||"Fonte não informada")+"</span></div><div class=\"application-role\">"+esc(r.role)+"<span>"+esc(r.work_model||r.location||"Modelo não informado")+"</span></div><time class=\"application-date\" datetime=\""+esc(r.applied_at||r.application_deadline||"")+"\">"+(r.status===preApplicationStatus?(r.application_deadline?fmt(r.application_deadline):"Sem prazo"):fmt(r.applied_at))+"<span>"+(r.status===preApplicationStatus?"Para candidatar":daysSince(r.applied_at))+"</span></time><span class=\"status-badge\">"+esc(r.status)+"</span><button class=\"row-menu\" type=\"button\" aria-label=\"Editar\">•••</button></article>").join("");e.list.querySelectorAll(".application-row").forEach(n=>n.querySelector("button").onclick=()=>openForm(rows.find(r=>String(r.id)===n.dataset.id)))}
async function load(){ready=true;e.warning.hidden=true;const{data,error}=await supabase.from("career_applications").select("*").order("applied_at",{ascending:false}).order("created_at",{ascending:false});if(error){if(error.code==="42P01"||/career_applications|schema cache|does not exist/i.test(error.message||"")){ready=false;rows=[];e.warning.hidden=false;render();return}throw error}rows=data||[];render()}
e.form.onsubmit=async ev=>{ev.preventDefault();if(!e.form.checkValidity()){e.form.reportValidity();return}const{data:{user}}=await supabase.auth.getUser();if(!user)return;e.save.disabled=true;e.save.textContent="Salvando…";if(e.status.value!==preApplicationStatus&&!e.date.value){e.msg.textContent="Informe a data da candidatura para este status.";e.msg.classList.add("is-error");e.save.disabled=false;e.save.textContent="Salvar candidatura";return}const payload={user_id:user.id,company:e.company.value.trim(),role:e.role.value.trim(),applied_at:e.status.value===preApplicationStatus?null:e.date.value,application_deadline:e.applicationDeadline.value||null,status:e.status.value,source:e.source.value||null,work_model:e.model.value||null,location:e.location.value.trim()||null,salary:e.salary.value.trim()||null,job_url:e.url.value.trim()||null,notes:e.notes.value.trim()||null};const q=e.id.value?supabase.from("career_applications").update(payload).eq("id",e.id.value):supabase.from("career_applications").insert(payload);const{error}=await q;e.save.disabled=false;e.save.textContent="Salvar candidatura";if(error){e.msg.textContent="Não foi possível salvar. Verifique a configuração do banco.";e.msg.classList.add("is-error");return}closeForm();await load()};
e.remove.onclick=async()=>{if(!e.id.value||!confirm("Excluir esta candidatura?"))return;await supabase.from("career_applications").delete().eq("id",e.id.value);closeForm();await load()};
e.newBtn.onclick=()=>ready?openForm():e.warning.scrollIntoView({behavior:"smooth"});e.exportBtn.onclick=exportCareer;
e.close.onclick=e.cancel.onclick=closeForm;
e.search.oninput=render;e.statusFilter.onchange=e.period.onchange=render;
e.logout.onclick=async()=>{await supabase.auth.signOut();location.href="./"};
(async()=>{const{data:{session}}=await supabase.auth.getSession();e.loading.hidden=true;if(!session){e.auth.hidden=false;return}e.view.hidden=false;try{await load()}catch{e.warning.hidden=false}})();
e.status.addEventListener("change",()=>{const pre=e.status.value===preApplicationStatus;if(pre){e.date.value=""}else if(!e.date.value){e.date.value=today()}});
