import {createClient} from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
import {SUPABASE_URL,SUPABASE_ANON_KEY} from "./supabase-config.js";
const supabase=createClient(SUPABASE_URL,SUPABASE_ANON_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=s=>document.querySelector(s);
const e={loading:$("#culture-loading"),auth:$("#culture-auth-required"),view:$("#culture-view"),logout:$("#logout-button"),newBtn:$("#new-culture-button"),dialog:$("#culture-dialog"),form:$("#culture-form"),close:$("#dialog-close"),cancel:$("#cancel-culture-button"),remove:$("#delete-culture-button"),save:$("#save-culture-button"),id:$("#culture-id"),type:$("#culture-type"),title:$("#culture-title"),creator:$("#culture-creator"),date:$("#culture-date"),genre:$("#culture-genre"),rating:$("#culture-rating"),platform:$("#culture-platform"),notes:$("#culture-notes"),msg:$("#culture-form-message"),search:$("#culture-search"),typeFilter:$("#type-filter"),yearFilter:$("#year-filter"),list:$("#culture-list"),empty:$("#culture-empty"),warning:$("#culture-setup-warning"),count:$("#culture-count"),kTotal:$("#kpi-total"),kMovies:$("#kpi-movies"),kBooks:$("#kpi-books"),kRating:$("#kpi-rating"),dialogTitle:$("#culture-dialog-title")};
let rows=[],ready=true,userId=null;
const today=()=>{const n=new Date(),x=new Date(n.getTime()-n.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)};
const fmt=d=>d?d.split("-").reverse().join("/"):"—";
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
function openForm(r){e.form.reset();e.id.value="";e.type.value="Filme";e.date.value=today();e.remove.hidden=true;e.dialogTitle.textContent="Novo registro";if(r){e.id.value=r.id;e.type.value=r.item_type;e.title.value=r.title||"";e.creator.value=r.creator||"";e.date.value=r.completed_at||today();e.genre.value=r.genre||"";e.rating.value=r.rating??"";e.platform.value=r.platform||"";e.notes.value=r.notes||"";e.remove.hidden=false;e.dialogTitle.textContent="Editar registro"}e.dialog.showModal();setTimeout(()=>e.title.focus(),0)}
function closeForm(){if(e.dialog.open)e.dialog.close()}
function filtered(){const q=e.search.value.trim().toLowerCase(),type=e.typeFilter.value,year=e.yearFilter.value,current=String(new Date().getFullYear());return rows.filter(r=>{const hay=(r.title+" "+(r.creator||"")).toLowerCase();if(q&&!hay.includes(q))return false;if(type!=="all"&&r.item_type!==type)return false;if(year==="current"&&!String(r.completed_at||"").startsWith(current))return false;return true})}
function render(){const current=String(new Date().getFullYear()),yearRows=rows.filter(r=>String(r.completed_at||"").startsWith(current));e.kTotal.textContent=yearRows.length;e.kMovies.textContent=yearRows.filter(r=>r.item_type==="Filme").length;e.kBooks.textContent=yearRows.filter(r=>r.item_type==="Livro").length;const rated=yearRows.filter(r=>Number.isFinite(Number(r.rating)));e.kRating.textContent=rated.length?(rated.reduce((s,r)=>s+Number(r.rating),0)/rated.length).toFixed(1).replace(".",","):"—";const data=filtered();e.count.textContent=data.length+" "+(data.length===1?"registro":"registros");e.empty.hidden=data.length!==0||!ready;e.list.innerHTML=data.map(r=>'<article class="culture-row" data-id="'+r.id+'"><span class="culture-type">'+esc(r.item_type)+'</span><div class="culture-main"><strong>'+esc(r.title)+'</strong><span>'+esc(r.genre||"Gênero não informado")+'</span></div><div class="culture-creator">'+esc(r.creator||"—")+'<span>'+esc(r.platform||"")+'</span></div><time class="culture-date">'+fmt(r.completed_at)+'</time><div class="culture-rating">'+(r.rating?esc(r.rating)+"/10":"—")+'</div><button class="row-menu" type="button" aria-label="Editar registro">•••</button></article>').join("");e.list.querySelectorAll(".culture-row").forEach(row=>row.querySelector(".row-menu").onclick=()=>openForm(rows.find(r=>r.id===row.dataset.id)))}
async function load(){ready=true;e.warning.hidden=true;const{data,error}=await supabase.from("culture_items").select("*").order("completed_at",{ascending:false}).order("created_at",{ascending:false});if(error){if(error.code==="42P01"||/culture_items|schema cache|does not exist/i.test(error.message||"")){ready=false;rows=[];e.warning.hidden=false;render();return}throw error}rows=data||[];render()}
e.form.onsubmit=async ev=>{ev.preventDefault();if(!e.form.checkValidity()){e.form.reportValidity();return}const payload={user_id:userId,item_type:e.type.value,title:e.title.value.trim(),creator:e.creator.value.trim()||null,completed_at:e.date.value,genre:e.genre.value.trim()||null,rating:e.rating.value?Number(e.rating.value):null,platform:e.platform.value.trim()||null,notes:e.notes.value.trim()||null};e.save.disabled=true;const q=e.id.value?supabase.from("culture_items").update(payload).eq("id",e.id.value):supabase.from("culture_items").insert(payload);const{error}=await q;e.save.disabled=false;if(error){e.msg.textContent="Não foi possível salvar.";e.msg.classList.add("is-error");return}closeForm();await load()};
e.remove.onclick=async()=>{if(!e.id.value||!confirm("Excluir este registro?"))return;await supabase.from("culture_items").delete().eq("id",e.id.value);closeForm();await load()};
e.newBtn.onclick=()=>ready?openForm():e.warning.scrollIntoView({behavior:"smooth"});e.close.onclick=e.cancel.onclick=closeForm;e.search.oninput=render;e.typeFilter.onchange=e.yearFilter.onchange=render;e.logout.onclick=async()=>{await supabase.auth.signOut();location.href="./"};
(async()=>{const{data:{session}}=await supabase.auth.getSession();e.loading.hidden=true;if(!session){e.auth.hidden=false;return}userId=session.user.id;e.view.hidden=false;try{await load()}catch{e.warning.hidden=false}})();