import {createClient} from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
import {SUPABASE_URL,SUPABASE_ANON_KEY} from "./supabase-config.js";
const supabase=createClient(SUPABASE_URL,SUPABASE_ANON_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=s=>document.querySelector(s);
const e={loading:$("#habits-loading"),auth:$("#habits-auth-required"),view:$("#habits-view"),logout:$("#logout-button"),newBtn:$("#new-habit-button"),dialog:$("#habit-dialog"),form:$("#habit-form"),close:$("#dialog-close"),cancel:$("#cancel-habit-button"),remove:$("#delete-habit-button"),save:$("#save-habit-button"),id:$("#habit-id"),name:$("#habit-name"),category:$("#habit-category"),target:$("#habit-target"),start:$("#habit-start"),notes:$("#habit-notes"),msg:$("#habit-form-message"),list:$("#habits-list"),empty:$("#habits-empty"),warning:$("#habits-setup-warning"),todayDate:$("#today-date"),active:$("#kpi-active-habits"),today:$("#kpi-today"),month:$("#kpi-month"),best:$("#kpi-best-streak"),title:$("#habit-dialog-title")};
let habits=[],logs=[],ready=true,userId=null;
const iso=d=>{const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)};
const today=()=>iso(new Date());
const monthStart=()=>{const d=new Date();d.setDate(1);return iso(d)};
const fmtLong=()=>new Intl.DateTimeFormat("pt-BR",{weekday:"long",day:"2-digit",month:"long"}).format(new Date());
function openForm(h){e.form.reset();e.id.value="";e.start.value=today();e.target.value="7";e.remove.hidden=true;e.title.textContent="Novo hábito";if(h){e.id.value=h.id;e.name.value=h.name||"";e.category.value=h.category||"";e.target.value=String(h.target_per_week||7);e.start.value=h.start_date||today();e.notes.value=h.notes||"";e.remove.hidden=false;e.title.textContent="Editar hábito"}e.dialog.showModal();setTimeout(()=>e.name.focus(),0)}
function closeForm(){if(e.dialog.open)e.dialog.close()}
function streakFor(habitId){const dates=logs.filter(l=>l.habit_id===habitId&&l.completed).map(l=>l.log_date).sort().reverse();if(!dates.length)return 0;let streak=0,cursor=new Date(today()+"T12:00:00");for(;;){const key=iso(cursor);if(dates.includes(key)){streak++;cursor.setDate(cursor.getDate()-1)}else break}return streak}
function render(){const active=habits.filter(h=>h.active!==false);const t=today();const todayDone=active.filter(h=>logs.some(l=>l.habit_id===h.id&&l.log_date===t&&l.completed)).length;e.active.textContent=active.length;e.today.textContent=(active.length?Math.round(todayDone/active.length*100):0)+"%";const monthLogs=logs.filter(l=>l.log_date>=monthStart()&&l.completed);const elapsed=new Date().getDate();const expected=active.reduce((sum,h)=>sum+Math.max(1,Math.round((h.target_per_week||7)*elapsed/7)),0);e.month.textContent=(expected?Math.min(100,Math.round(monthLogs.length/expected*100)):0)+"%";e.best.textContent=active.reduce((m,h)=>Math.max(m,streakFor(h.id)),0);e.empty.hidden=active.length!==0||!ready;e.list.innerHTML=active.map(h=>{const done=logs.some(l=>l.habit_id===h.id&&l.log_date===t&&l.completed);return '<article class="habit-row" data-id="'+h.id+'"><button class="habit-check '+(done?"is-done":"")+'" type="button" aria-label="'+(done?"Desmarcar":"Marcar")+' '+h.name+'">'+(done?"✓":"")+'</button><div class="habit-main"><strong>'+h.name+'</strong><span>'+(h.category||"Sem categoria")+'</span></div><div class="habit-meta">'+(h.target_per_week||7)+'x por semana</div><div class="habit-streak">'+streakFor(h.id)+' dias</div><button class="row-menu" type="button" aria-label="Editar hábito">•••</button></article>'}).join("");e.list.querySelectorAll(".habit-row").forEach(row=>{const id=row.dataset.id;row.querySelector(".habit-check").onclick=()=>toggleToday(id);row.querySelector(".row-menu").onclick=()=>openForm(habits.find(h=>h.id===id))})}
async function load(){ready=true;e.warning.hidden=true;const[{data:h,error:he},{data:l,error:le}]=await Promise.all([supabase.from("habits").select("*").order("created_at"),supabase.from("habit_logs").select("*").gte("log_date",monthStart()).order("log_date")]);if(he||le){const err=he||le;if(err.code==="42P01"||/habits|habit_logs|schema cache|does not exist/i.test(err.message||"")){ready=false;habits=[];logs=[];e.warning.hidden=false;render();return}throw err}habits=h||[];logs=l||[];render()}
async function toggleToday(id){const t=today(),existing=logs.find(l=>l.habit_id===id&&l.log_date===t);if(existing){await supabase.from("habit_logs").delete().eq("id",existing.id)}else{await supabase.from("habit_logs").insert({user_id:userId,habit_id:id,log_date:t,completed:true})}await load()}
e.form.onsubmit=async ev=>{ev.preventDefault();if(!e.form.checkValidity()){e.form.reportValidity();return}const payload={user_id:userId,name:e.name.value.trim(),category:e.category.value||null,target_per_week:Number(e.target.value),start_date:e.start.value||today(),notes:e.notes.value.trim()||null,active:true};e.save.disabled=true;const q=e.id.value?supabase.from("habits").update(payload).eq("id",e.id.value):supabase.from("habits").insert(payload);const{error}=await q;e.save.disabled=false;if(error){e.msg.textContent="Não foi possível salvar.";e.msg.classList.add("is-error");return}closeForm();await load()};
e.remove.onclick=async()=>{if(!e.id.value||!confirm("Excluir este hábito e seu histórico?"))return;await supabase.from("habits").delete().eq("id",e.id.value);closeForm();await load()};
e.newBtn.onclick=()=>ready?openForm():e.warning.scrollIntoView({behavior:"smooth"});e.close.onclick=e.cancel.onclick=closeForm;e.logout.onclick=async()=>{await supabase.auth.signOut();location.href="./"};
(async()=>{const{data:{session}}=await supabase.auth.getSession();e.loading.hidden=true;if(!session){e.auth.hidden=false;return}userId=session.user.id;e.view.hidden=false;e.todayDate.textContent=fmtLong();try{await load()}catch{e.warning.hidden=false}})();