import {createClient} from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
import {SUPABASE_URL,SUPABASE_ANON_KEY} from "./supabase-config.js";
const supabase=createClient(SUPABASE_URL,SUPABASE_ANON_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const $=s=>document.querySelector(s);
const e={loading:$("#goals-loading"),auth:$("#goals-auth-required"),view:$("#goals-view"),logout:$("#logout-button"),newBtn:$("#new-goal-button"),dialog:$("#goal-dialog"),form:$("#goal-form"),close:$("#dialog-close"),cancel:$("#cancel-goal-button"),remove:$("#delete-goal-button"),save:$("#save-goal-button"),id:$("#goal-id"),title:$("#goal-title"),period:$("#goal-period"),category:$("#goal-category"),deadline:$("#goal-deadline"),status:$("#goal-status"),progress:$("#goal-progress"),progressLabel:$("#goal-progress-label"),notes:$("#goal-notes"),msg:$("#goal-form-message"),search:$("#goals-search"),periodFilter:$("#period-filter"),statusFilter:$("#status-filter"),list:$("#goals-list"),empty:$("#goals-empty"),warning:$("#goals-setup-warning"),count:$("#goals-count"),kActive:$("#kpi-active"),kCompleted:$("#kpi-completed"),kProgress:$("#kpi-progress"),kDue:$("#kpi-due"),dialogTitle:$("#goal-dialog-title")};
let rows=[],ready=true,userId=null;
const today=()=>{const n=new Date(),x=new Date(n.getTime()-n.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)};
const fmt=d=>d?d.split("-").reverse().join("/"):"—";
const daysUntil=d=>{if(!d)return null;const a=new Date(today()+"T12:00:00"),b=new Date(d+"T12:00:00");return Math.round((b-a)/86400000)};
function deadlineLabel(r){if(r.status==="Concluída")return "Concluída";const days=daysUntil(r.deadline);if(days===null)return "Sem prazo";if(days<0)return "Atrasada "+Math.abs(days)+"d";if(days===0)return "Hoje";if(days===1)return "Amanhã";return "Em "+days+" dias"}
function openForm(r){e.form.reset();e.id.value="";e.period.value="Mensal";e.status.value="Em andamento";e.progress.value="0";e.progressLabel.textContent="0%";e.deadline.value=today();e.remove.hidden=true;e.dialogTitle.textContent="Nova meta";if(r){e.id.value=r.id;e.title.value=r.title||"";e.period.value=r.period_type||"Mensal";e.category.value=r.category||"";e.deadline.value=r.deadline||today();e.status.value=r.status||"Em andamento";e.progress.value=String(r.progress||0);e.progressLabel.textContent=(r.progress||0)+"%";e.notes.value=r.notes||"";e.remove.hidden=false;e.dialogTitle.textContent="Editar meta"}e.dialog.showModal();setTimeout(()=>e.title.focus(),0)}
function closeForm(){if(e.dialog.open)e.dialog.close()}
function filtered(){const q=e.search.value.trim().toLowerCase(),p=e.periodFilter.value,s=e.statusFilter.value;return rows.filter(r=>{if(q&&!r.title.toLowerCase().includes(q))return false;if(p!=="all"&&r.period_type!==p)return false;if(s==="active"&&r.status==="Concluída")return false;if(s!=="active"&&s!=="all"&&r.status!==s)return false;return true})}
function render(){const active=rows.filter(r=>r.status!=="Concluída"),completed=rows.filter(r=>r.status==="Concluída");e.kActive.textContent=active.length;e.kCompleted.textContent=completed.length;e.kProgress.textContent=(active.length?Math.round(active.reduce((sum,r)=>sum+Number(r.progress||0),0)/active.length):0)+"%";e.kDue.textContent=active.filter(r=>{const d=daysUntil(r.deadline);return d!==null&&d>=0&&d<=7}).length;const data=filtered();e.count.textContent=data.length+" "+(data.length===1?"registro":"registros");e.empty.hidden=data.length!==0||!ready;e.list.innerHTML=data.map(r=>{const days=daysUntil(r.deadline),cls=r.status!=="Concluída"&&days!==null&&days<0?" is-overdue":r.status!=="Concluída"&&days!==null&&days<=7?" is-soon":"";return '<article class="goal-row" data-id="'+r.id+'"><div class="goal-main"><strong>'+r.title+'</strong><span>'+(r.category||"Sem categoria")+' · '+r.status+'</span></div><span class="goal-period">'+r.period_type+'</span><div class="goal-progress-wrap"><div class="goal-progress-top"><span>Progresso</span><strong>'+r.progress+'%</strong></div><div class="goal-progress-bar"><div class="goal-progress-fill" style="width:'+r.progress+'%"></div></div></div><div class="goal-deadline'+cls+'">'+deadlineLabel(r)+'<br><span>'+fmt(r.deadline)+'</span></div><button class="row-menu" type="button" aria-label="Editar meta">•••</button></article>'}).join("");e.list.querySelectorAll(".goal-row").forEach(row=>row.querySelector(".row-menu").onclick=()=>openForm(rows.find(r=>r.id===row.dataset.id)))}
async function load(){ready=true;e.warning.hidden=true;const{data,error}=await supabase.from("goals").select("*").order("deadline",{ascending:true}).order("created_at",{ascending:false});if(error){if(error.code==="42P01"||/goals|schema cache|does not exist/i.test(error.message||"")){ready=false;rows=[];e.warning.hidden=false;render();return}throw error}rows=data||[];render()}
e.progress.oninput=()=>e.progressLabel.textContent=e.progress.value+"%";
e.status.onchange=()=>{if(e.status.value==="Concluída"){e.progress.value="100";e.progressLabel.textContent="100%"}};
e.form.onsubmit=async ev=>{ev.preventDefault();if(!e.form.checkValidity()){e.form.reportValidity();return}const payload={user_id:userId,title:e.title.value.trim(),period_type:e.period.value,category:e.category.value||null,deadline:e.deadline.value,status:e.status.value,progress:Number(e.progress.value),notes:e.notes.value.trim()||null};e.save.disabled=true;const q=e.id.value?supabase.from("goals").update(payload).eq("id",e.id.value):supabase.from("goals").insert(payload);const{error}=await q;e.save.disabled=false;if(error){e.msg.textContent="Não foi possível salvar.";e.msg.classList.add("is-error");return}closeForm();await load()};
e.remove.onclick=async()=>{if(!e.id.value||!confirm("Excluir esta meta?"))return;await supabase.from("goals").delete().eq("id",e.id.value);closeForm();await load()};
e.newBtn.onclick=()=>ready?openForm():e.warning.scrollIntoView({behavior:"smooth"});e.close.onclick=e.cancel.onclick=closeForm;e.search.oninput=render;e.periodFilter.onchange=e.statusFilter.onchange=render;e.logout.onclick=async()=>{await supabase.auth.signOut();location.href="./"};
(async()=>{const{data:{session}}=await supabase.auth.getSession();e.loading.hidden=true;if(!session){e.auth.hidden=false;return}userId=session.user.id;e.view.hidden=false;try{await load()}catch{e.warning.hidden=false}})();